### ISSUE TITLE
Error: CONNECTION ERROR: Couldn't connect to node on WS.

### ISSUE THREAD

**Issue by pavanyogi** [blocknative/sdk#162]
We are trying to set up it from the repository sample code. But we are getting this error. 

Error: CONNECTION ERROR: Couldn't connect to node on WS.

/home/pavany/Documents/aux/qbix/bnc-nofity-sdk/node_modules/web3-core-helpers/lib/errors.js:66
        const error = new Error(msg);
                      ^

Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.ConnectionError (/home/pavany/Documents/aux/qbix/bnc-nofity-sdk/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.InvalidConnection (/home/pavany/Documents/aux/qbix/bnc-nofity-sdk/node_modules/web3-core-helpers/lib/errors.js:36:21)
    at /home/pavany/Documents/aux/qbix/bnc-nofity-sdk/node_modules/web3-providers-ws/lib/index.js:161:37
    at Map.forEach (<anonymous>)
    at WebsocketProvider._onClose (/home/pavany/Documents/aux/qbix/bnc-nofity-sdk/node_modules/web3-providers-ws/lib/index.js:160:28)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/pavany/Documents/aux/qbix/bnc-nofity-sdk/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onClose (/home/pavany/Documents/aux/qbix/bnc-nofity-sdk/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/home/pavany/Documents/aux/qbix/bnc-nofity-sdk/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:390:28)
    at WebSocketConnection.handleSocketClose (/home/pavany/Documents/aux/qbix/bnc-nofity-sdk/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at TLSSocket.emit (node:events:402:35)
    at node:net:687:12
    at TCP.done (node:_tls_wrap:580:7) {
  code: 1006,
  reason: 'Connection dropped by remote peer.'
}
package.json
```json
{
  "name": "blocknative-transaction",
  "type": "module",
  "target": "commonjs",
  "version": "0.1.0",
  "description": "print transactions using blocknative sdk",
  "main": "App2.js",
  "scripts": {
    "start": "node ./App2.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bnc-sdk": "^3.7.0",
    "web3": "1.5.1",
    "ws": "^8.2.3"
  }
}
```
App2.js
```js
import WebSocket from 'ws';
import BlocknativeSdk from 'bnc-sdk';
import Web3 from 'web3';

const wsapi_url = 'wss://api.blocknative.com/v0';

const web3 = new Web3(wsapi_url);

// create options object
const options = {
  dappId: process.env.BN_API_KEY,
  ws: WebSocket,
  networkId: 1,
  transactionHandlers: [(event) => console.log(event.transaction)],
};

// initialize and connect to the api
const blocknative = new BlocknativeSdk(options);

const txOptions = {
  from: '0xfb0b402bf84f8b7bdfc0df904240bc26928d612d',
  to: '0xf9fae6fb9dce72e385ca73d2bfdf1b409dbd8d66',
};

// initiate a transaction via web3.js
web3.eth.sendTransaction(txOptions).on('transactionHash', (hash) => {
  // call with the transaction hash of the transaction that you would like to receive status updates for
  const { emitter } = blocknative.transaction(hash);

  // listen to some events
  emitter.on('txPool', (transaction) => {
    console.log(`Sending ${transaction.value} wei to ${transaction.to}`);
  });

  emitter.on('txConfirmed', (transaction) => {
    console.log('Transaction is confirmed!');
  });

  // catch every other event that occurs and log it
  emitter.on('all', (transaction) => {
    console.log(`Transaction event: ${transaction.eventCode}`);
  });
});

```
```bash
node -v
v16.13.1

npm -v
8.1.4
```

**Comment by pavanyogi** [comment]
If anyone can help to resolve the above issue?

**Comment by taylorjdawson** [comment]
@pavanyogi This isn't an issue with the sdk but rather the API itself. Please [join our discord](https://discord.gg/vMJVty7b) to get updates on services outages and degradation. 👍🏾
